package com.app.demo.constraint;


public class Contrainst {
	public static String html = "<!DOCTYPE html>\r\n"
			+ "<html lang=\"vi\">\r\n"
			+ "<head>\r\n"
			+ "	<meta charset=\"UTF-8\">\r\n"
			+ "	<link rel=\"profile\" href=\"https://gmpg.org/xfn/11\">\r\n"
			+ "	\r\n"
			+ "	<!-- This site is optimized with the Yoast SEO plugin v15.8 - https://yoast.com/wordpress/plugins/seo/ -->\r\n"
			+ "	<title>Major Education - Giỏi tiếng Anh, nhanh thành tài! - Major Education</title>\r\n"
			+ "	<meta name=\"robots\" content=\"index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1\" />\r\n"
			+ "	<link rel=\"canonical\" href=\"http://major.edu.vn/\" />\r\n"
			+ "	<meta property=\"og:locale\" content=\"vi_VN\" />\r\n"
			+ "	<meta property=\"og:type\" content=\"website\" />\r\n"
			+ "	<meta property=\"og:title\" content=\"Major Education - Giỏi tiếng Anh, nhanh thành tài! - Major Education\" />\r\n"
			+ "	\r\n"
			+ "	<meta property=\"og:url\" content=\"http://major.edu.vn/\" />\r\n"
			+ "	<meta property=\"og:site_name\" content=\"Major Education\" />\r\n"
			+ "	<meta property=\"og:image:width\" content=\"950\" />\r\n"
			+ "	<meta property=\"og:image:height\" content=\"900\" />\r\n"
			+ "	<meta name=\"twitter:card\" content=\"summary_large_image\" />\r\n"
			+ "	<script type=\"application/ld+json\" class=\"yoast-schema-graph\">{\"@context\":\"https://schema.org\",\"@graph\":[{\"@type\":\"WebSite\",\"@id\":\"http://major.edu.vn/#website\",\"url\":\"http://major.edu.vn/\",\"name\":\"Major Education\",\"description\":\"Gi\\u1ecfi Ti\\u1ebfng Anh, Nhanh Th\\u00e0nh T\\u00e0i\",\"potentialAction\":[{\"@type\":\"SearchAction\",\"target\":\"http://major.edu.vn/?s={search_term_string}\",\"query-input\":\"required name=search_term_string\"}],\"inLanguage\":\"vi\"},{\"@type\":\"ImageObject\",\"@id\":\"http://major.edu.vn/#primaryimage\",\"inLanguage\":\"vi\",\"url\":\"http://major.edu.vn/wp-content/uploads/2020/10/giao-vien-major-education-2020.png\",\"width\":950,\"height\":900},{\"@type\":\"WebPage\",\"@id\":\"http://major.edu.vn/#webpage\",\"url\":\"http://major.edu.vn/\",\"name\":\"Major Education - Gi\\u1ecfi ti\\u1ebfng Anh, nhanh th\\u00e0nh t\\u00e0i! - Major Education\",\"isPartOf\":{\"@id\":\"http://major.edu.vn/#website\"},\"primaryImageOfPage\":{\"@id\":\"http://major.edu.vn/#primaryimage\"},\"datePublished\":\"2020-02-06T09:21:41+00:00\",\"dateModified\":\"2021-03-18T08:30:22+00:00\",\"breadcrumb\":{\"@id\":\"http://major.edu.vn/#breadcrumb\"},\"inLanguage\":\"vi\",\"potentialAction\":[{\"@type\":\"ReadAction\",\"target\":[\"http://major.edu.vn/\"]}]},{\"@type\":\"BreadcrumbList\",\"@id\":\"http://major.edu.vn/#breadcrumb\",\"itemListElement\":[{\"@type\":\"ListItem\",\"position\":1,\"item\":{\"@type\":\"WebPage\",\"@id\":\"http://major.edu.vn/\",\"url\":\"http://major.edu.vn/\",\"name\":\"Home\"}}]}]}</script>\r\n"
			+ "	<!-- / Yoast SEO plugin. -->\r\n"
			+ "\r\n"
			+ "\r\n"
			+ "<link rel='dns-prefetch' href='//s.w.org' />\r\n"
			+ "<link rel=\"alternate\" type=\"application/rss+xml\" title=\"Dòng thông tin Major Education &raquo;\" href=\"http://major.edu.vn/feed/\" />\r\n"
			+ "<link rel=\"alternate\" type=\"application/rss+xml\" title=\"Dòng phản hồi Major Education &raquo;\" href=\"http://major.edu.vn/comments/feed/\" />\r\n"
			+ "		<script>\r\n"
			+ "			window._wpemojiSettings = {\"baseUrl\":\"https:\\/\\/s.w.org\\/images\\/core\\/emoji\\/13.0.1\\/72x72\\/\",\"ext\":\".png\",\"svgUrl\":\"https:\\/\\/s.w.org\\/images\\/core\\/emoji\\/13.0.1\\/svg\\/\",\"svgExt\":\".svg\",\"source\":{\"concatemoji\":\"http:\\/\\/major.edu.vn\\/wp-includes\\/js\\/wp-emoji-release.min.js?ver=5.6.2\"}};\r\n"
			+ "			!function(e,a,t){var n,r,o,i=a.createElement(\"canvas\"),p=i.getContext&&i.getContext(\"2d\");function s(e,t){var a=String.fromCharCode;p.clearRect(0,0,i.width,i.height),p.fillText(a.apply(this,e),0,0);e=i.toDataURL();return p.clearRect(0,0,i.width,i.height),p.fillText(a.apply(this,t),0,0),e===i.toDataURL()}function c(e){var t=a.createElement(\"script\");t.src=e,t.defer=t.type=\"text/javascript\",a.getElementsByTagName(\"head\")[0].appendChild(t)}for(o=Array(\"flag\",\"emoji\"),t.supports={everything:!0,everythingExceptFlag:!0},r=0;r<o.length;r++)t.supports[o[r]]=function(e){if(!p||!p.fillText)return!1;switch(p.textBaseline=\"top\",p.font=\"600 32px Arial\",e){case\"flag\":return s([127987,65039,8205,9895,65039],[127987,65039,8203,9895,65039])?!1:!s([55356,56826,55356,56819],[55356,56826,8203,55356,56819])&&!s([55356,57332,56128,56423,56128,56418,56128,56421,56128,56430,56128,56423,56128,56447],[55356,57332,8203,56128,56423,8203,56128,56418,8203,56128,56421,8203,56128,56430,8203,56128,56423,8203,56128,56447]);case\"emoji\":return!s([55357,56424,8205,55356,57212],[55357,56424,8203,55356,57212])}return!1}(o[r]),t.supports.everything=t.supports.everything&&t.supports[o[r]],\"flag\"!==o[r]&&(t.supports.everythingExceptFlag=t.supports.everythingExceptFlag&&t.supports[o[r]]);t.supports.everythingExceptFlag=t.supports.everythingExceptFlag&&!t.supports.flag,t.DOMReady=!1,t.readyCallback=function(){t.DOMReady=!0},t.supports.everything||(n=function(){t.readyCallback()},a.addEventListener?(a.addEventListener(\"DOMContentLoaded\",n,!1),e.addEventListener(\"load\",n,!1)):(e.attachEvent(\"onload\",n),a.attachEvent(\"onreadystatechange\",function(){\"complete\"===a.readyState&&t.readyCallback()})),(n=t.source||{}).concatemoji?c(n.concatemoji):n.wpemoji&&n.twemoji&&(c(n.twemoji),c(n.wpemoji)))}(window,document,window._wpemojiSettings);\r\n"
			+ "		</script>\r\n"
			+ "		<style>\r\n"
			+ "img.wp-smiley,\r\n"
			+ "img.emoji {\r\n"
			+ "	display: inline !important;\r\n"
			+ "	border: none !important;\r\n"
			+ "	box-shadow: none !important;\r\n"
			+ "	height: 1em !important;\r\n"
			+ "	width: 1em !important;\r\n"
			+ "	margin: 0 .07em !important;\r\n"
			+ "	vertical-align: -0.1em !important;\r\n"
			+ "	background: none !important;\r\n"
			+ "	padding: 0 !important;\r\n"
			+ "}\r\n"
			+ "</style>\r\n"
			+ "<link rel='stylesheet' id='wp-block-library-css'  href='http://major.edu.vn/wp-includes/css/dist/block-library/style.min.css?ver=5.6.2' media='all' />\r\n"
			+ "<link rel='stylesheet' id='image-hover-effects-css-css'  href='http://major.edu.vn/wp-content/plugins/mega-addons-for-visual-composer/css/ihover.css?ver=5.6.2' media='all' />\r\n"
			+ "<link rel='stylesheet' id='style-css-css'  href='http://major.edu.vn/wp-content/plugins/mega-addons-for-visual-composer/css/style.css?ver=5.6.2' media='all' />\r\n"
			+ "<link rel='stylesheet' id='font-awesome-latest-css'  href='http://major.edu.vn/wp-content/plugins/mega-addons-for-visual-composer/css/font-awesome/css/all.css?ver=5.6.2' media='all' />\r\n"
			+ "<link rel='stylesheet' id='cb70d11b8-css'  href='http://major.edu.vn/wp-content/uploads/essential-addons-elementor/cb70d11b8.min.css?ver=1616279248' media='all' />\r\n"
			+ "<link rel='stylesheet' id='generate-style-grid-css'  href='http://major.edu.vn/wp-content/themes/generatepress/assets/css/unsemantic-grid.min.css?ver=3.0.2' media='all' />\r\n"
			+ "<link rel='stylesheet' id='generate-style-css'  href='http://major.edu.vn/wp-content/themes/generatepress/assets/css/style.min.css?ver=3.0.2' media='all' />\r\n"
			+ "<style id='generate-style-inline-css'>\r\n"
			+ ".generate-page-header, .page-header-image, .page-header-image-single {display:none}\r\n"
			+ "body{background-color:#efefef;color:#3a3a3a;}a{color:#1e73be;}a:hover, a:focus, a:active{color:#000000;}body .grid-container{max-width:1100px;}.wp-block-group__inner-container{max-width:1100px;margin-left:auto;margin-right:auto;}.site-header .header-image{width:250px;}body, button, input, select, textarea{font-family:-apple-system, system-ui, BlinkMacSystemFont, \"Segoe UI\", Helvetica, Arial, sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\";}body{line-height:1.5;}.entry-content > [class*=\"wp-block-\"]:not(:last-child){margin-bottom:1.5em;}.main-navigation a, .menu-toggle{font-weight:700;}.main-navigation .main-nav ul ul li a{font-size:14px;}.sidebar .widget, .footer-widgets .widget{font-size:17px;}h1{font-weight:300;font-size:40px;}h2{font-weight:300;font-size:30px;}h3{font-size:20px;}h4{font-size:inherit;}h5{font-size:inherit;}@media (max-width:768px){.main-title{font-size:20px;}h1{font-size:30px;}h2{font-size:25px;}}.top-bar{background-color:#636363;color:#ffffff;}.top-bar a{color:#ffffff;}.top-bar a:hover{color:#303030;}.site-header{background-color:#ffffff;color:#3a3a3a;}.site-header a{color:#3a3a3a;}.main-title a,.main-title a:hover{color:#f1c40f;}.site-description{color:#757575;}.main-navigation,.main-navigation ul ul{background-color:#f1c40f;}.main-navigation .main-nav ul li a,.menu-toggle, .main-navigation .menu-bar-items{color:#262261;}.main-navigation .main-nav ul li:hover > a,.main-navigation .main-nav ul li:focus > a, .main-navigation .main-nav ul li.sfHover > a, .main-navigation .menu-bar-item:hover > a, .main-navigation .menu-bar-item.sfHover > a{color:#f1c40f;background-color:#262261;}button.menu-toggle:hover,button.menu-toggle:focus,.main-navigation .mobile-bar-items a,.main-navigation .mobile-bar-items a:hover,.main-navigation .mobile-bar-items a:focus{color:#262261;}.main-navigation .main-nav ul li[class*=\"current-menu-\"] > a{color:#f1c40f;background-color:#262261;}.main-navigation .main-nav ul li[class*=\"current-menu-\"] > a:hover,.main-navigation .main-nav ul li[class*=\"current-menu-\"].sfHover > a{color:#f1c40f;background-color:#262261;}.navigation-search input[type=\"search\"],.navigation-search input[type=\"search\"]:active, .navigation-search input[type=\"search\"]:focus, .main-navigation .main-nav ul li.search-item.active > a, .main-navigation .menu-bar-items .search-item.active > a{color:#f1c40f;background-color:#262261;}.main-navigation ul ul{background-color:#3f3f3f;}.main-navigation .main-nav ul ul li a{color:#ffffff;}.main-navigation .main-nav ul ul li:hover > a,.main-navigation .main-nav ul ul li:focus > a,.main-navigation .main-nav ul ul li.sfHover > a{color:#ffffff;background-color:#4f4f4f;}.main-navigation .main-nav ul ul li[class*=\"current-menu-\"] > a{color:#ffffff;background-color:#4f4f4f;}.main-navigation .main-nav ul ul li[class*=\"current-menu-\"] > a:hover,.main-navigation .main-nav ul ul li[class*=\"current-menu-\"].sfHover > a{color:#ffffff;background-color:#4f4f4f;}.separate-containers .inside-article, .separate-containers .comments-area, .separate-containers .page-header, .one-container .container, .separate-containers .paging-navigation, .inside-page-header{color:#262261;background-color:#ffffff;}.inside-article a,.paging-navigation a,.comments-area a,.page-header a{color:#262261;}.inside-article a:hover,.paging-navigation a:hover,.comments-area a:hover,.page-header a:hover{color:#1abc9c;}.entry-meta{color:#262261;}.entry-meta a{color:#262261;}.entry-meta a:hover{color:#1e73be;}h1{color:#262261;}h2{color:#262261;}h3{color:#262261;}h4{color:#262261;}h5{color:#262261;}.sidebar .widget{color:#f1c40f;background-color:#262261;}.sidebar .widget a{color:#efefef;}.sidebar .widget a:hover{color:#f1c40f;}.sidebar .widget .widget-title{color:#f1c40f;}.footer-widgets{background-color:#f1c40f;}.footer-widgets .widget-title{color:#000000;}.site-info{color:#ffffff;background-color:#262261;}.site-info a{color:#ffffff;}.site-info a:hover{color:#606060;}.footer-bar .widget_nav_menu .current-menu-item a{color:#606060;}input[type=\"text\"],input[type=\"email\"],input[type=\"url\"],input[type=\"password\"],input[type=\"search\"],input[type=\"tel\"],input[type=\"number\"],textarea,select{color:#666666;background-color:#fafafa;border-color:#cccccc;}input[type=\"text\"]:focus,input[type=\"email\"]:focus,input[type=\"url\"]:focus,input[type=\"password\"]:focus,input[type=\"search\"]:focus,input[type=\"tel\"]:focus,input[type=\"number\"]:focus,textarea:focus,select:focus{color:#666666;background-color:#ffffff;border-color:#bfbfbf;}button,html input[type=\"button\"],input[type=\"reset\"],input[type=\"submit\"],a.button,a.wp-block-button__link:not(.has-background){color:#ffffff;background-color:#666666;}button:hover,html input[type=\"button\"]:hover,input[type=\"reset\"]:hover,input[type=\"submit\"]:hover,a.button:hover,button:focus,html input[type=\"button\"]:focus,input[type=\"reset\"]:focus,input[type=\"submit\"]:focus,a.button:focus,a.wp-block-button__link:not(.has-background):active,a.wp-block-button__link:not(.has-background):focus,a.wp-block-button__link:not(.has-background):hover{color:#ffffff;background-color:#3f3f3f;}a.generate-back-to-top{background-color:rgba( 0,0,0,0.4 );color:#ffffff;}a.generate-back-to-top:hover,a.generate-back-to-top:focus{background-color:rgba( 0,0,0,0.6 );color:#ffffff;}@media (max-width: 768px){.main-navigation .menu-bar-item:hover > a, .main-navigation .menu-bar-item.sfHover > a{background:none;color:#262261;}}.inside-top-bar{padding:10px;}.inside-header{padding:20px;}.entry-content .alignwide, body:not(.no-sidebar) .entry-content .alignfull{margin-left:-40px;width:calc(100% + 80px);max-width:calc(100% + 80px);}.main-navigation .main-nav ul li a,.menu-toggle,.main-navigation .mobile-bar-items a{line-height:70px;}.navigation-search input[type=\"search\"]{height:70px;}.rtl .menu-item-has-children .dropdown-menu-toggle{padding-left:20px;}.rtl .main-navigation .main-nav ul li.menu-item-has-children > a{padding-right:20px;}.widget-area .widget{padding:20px;}.site-info{padding:20px;}@media (max-width:768px){.separate-containers .inside-article, .separate-containers .comments-area, .separate-containers .page-header, .separate-containers .paging-navigation, .one-container .site-content, .inside-page-header, .wp-block-group__inner-container{padding:30px;}.site-info{padding-right:10px;padding-left:10px;}.entry-content .alignwide, body:not(.no-sidebar) .entry-content .alignfull{margin-left:-30px;width:calc(100% + 60px);max-width:calc(100% + 60px);}}@media (max-width: 768px){.main-navigation .menu-toggle,.main-navigation .mobile-bar-items,.sidebar-nav-mobile:not(#sticky-placeholder){display:block;}.main-navigation ul,.gen-sidebar-nav{display:none;}[class*=\"nav-float-\"] .site-header .inside-header > *{float:none;clear:both;}}\r\n"
			+ ".navigation-branding .main-title{font-weight:bold;text-transform:none;font-size:25px;}@media (max-width: 768px){.navigation-branding .main-title{font-size:20px;}}\r\n"
			+ "</style>\r\n"
			+ "<link rel='stylesheet' id='generate-mobile-style-css'  href='http://major.edu.vn/wp-content/themes/generatepress/assets/css/mobile.min.css?ver=3.0.2' media='all' />\r\n"
			+ "<link rel='stylesheet' id='generate-font-icons-css'  href='http://major.edu.vn/wp-content/themes/generatepress/assets/css/components/font-icons.min.css?ver=3.0.2' media='all' />\r\n"
			+ "<link rel='stylesheet' id='font-awesome-css'  href='http://major.edu.vn/wp-content/plugins/js_composer/assets/lib/bower/font-awesome/css/font-awesome.min.css?ver=6.0.1' media='all' />\r\n"
			+ "<!--[if lt IE 9]>\r\n"
			+ "<link rel='stylesheet' id='vc_lte_ie9-css'  href='http://major.edu.vn/wp-content/plugins/js_composer/assets/css/vc_lte_ie9.min.css?ver=6.0.1' media='screen' />\r\n"
			+ "<![endif]-->\r\n"
			+ "<link rel='stylesheet' id='elementor-icons-css'  href='http://major.edu.vn/wp-content/plugins/elementor/assets/lib/eicons/css/elementor-icons.min.css?ver=5.10.0' media='all' />\r\n"
			+ "<style id='elementor-icons-inline-css'>\r\n"
			+ "\r\n"
			+ "		.elementor-add-new-section .elementor-add-templately-promo-button{\r\n"
			+ "            background-color: #5d4fff;\r\n"
			+ "            background-image: url(http://major.edu.vn/wp-content/plugins/essential-addons-for-elementor-lite/assets/admin/images/templately/logo-icon.svg);\r\n"
			+ "            background-repeat: no-repeat;\r\n"
			+ "            background-position: center center;\r\n"
			+ "            margin-left: 5px;\r\n"
			+ "            position: relative;\r\n"
			+ "            bottom: 5px;\r\n"
			+ "        }\r\n"
			+ "</style>\r\n"
			+ "<link rel='stylesheet' id='elementor-animations-css'  href='http://major.edu.vn/wp-content/plugins/elementor/assets/lib/animations/animations.min.css?ver=3.1.1' media='all' />\r\n"
			+ "<link rel='stylesheet' id='elementor-frontend-legacy-css'  href='http://major.edu.vn/wp-content/plugins/elementor/assets/css/frontend-legacy.min.css?ver=3.1.1' media='all' />\r\n"
			+ "<link rel='stylesheet' id='elementor-frontend-css'  href='http://major.edu.vn/wp-content/plugins/elementor/assets/css/frontend.min.css?ver=3.1.1' media='all' />\r\n"
			+ "<link rel='stylesheet' id='elementor-post-13630-css'  href='http://major.edu.vn/wp-content/uploads/elementor/css/post-13630.css?ver=1613728498' media='all' />\r\n"
			+ "<link rel='stylesheet' id='elementor-global-css'  href='http://major.edu.vn/wp-content/uploads/elementor/css/global.css?ver=1613728499' media='all' />\r\n"
			+ "<link rel='stylesheet' id='elementor-post-215-css'  href='http://major.edu.vn/wp-content/uploads/elementor/css/post-215.css?ver=1616056226' media='all' />\r\n"
			+ "<link rel='stylesheet' id='generate-blog-images-css'  href='http://major.edu.vn/wp-content/plugins/gp-premium/blog/functions/css/featured-images.min.css?ver=1.12.3' media='all' />\r\n"
			+ "<link rel='stylesheet' id='generate-navigation-branding-css'  href='http://major.edu.vn/wp-content/plugins/gp-premium/menu-plus/functions/css/navigation-branding.min.css?ver=1.12.3' media='all' />\r\n"
			+ "<style id='generate-navigation-branding-inline-css'>\r\n"
			+ ".navigation-branding img, .site-logo.mobile-header-logo img{height:70px;width:auto;}.navigation-branding .main-title{line-height:70px;}@media (max-width: 1110px){#site-navigation .navigation-branding, #sticky-navigation .navigation-branding{margin-left:10px;}}@media (max-width: 768px){.main-navigation:not(.slideout-navigation) .main-nav{-ms-flex:0 0 100%;flex:0 0 100%;}.main-navigation:not(.slideout-navigation) .inside-navigation{-ms-flex-wrap:wrap;flex-wrap:wrap;display:-webkit-box;display:-ms-flexbox;display:flex;}.nav-aligned-center .navigation-branding, .nav-aligned-left .navigation-branding{margin-right:auto;}.nav-aligned-center  .main-navigation.has-branding:not(.slideout-navigation) .inside-navigation .main-nav,.nav-aligned-center  .main-navigation.has-sticky-branding.navigation-stick .inside-navigation .main-nav,.nav-aligned-left  .main-navigation.has-branding:not(.slideout-navigation) .inside-navigation .main-nav,.nav-aligned-left  .main-navigation.has-sticky-branding.navigation-stick .inside-navigation .main-nav{margin-right:0px;}}\r\n"
			+ "</style>\r\n"
			+ "<link rel='stylesheet' id='google-fonts-1-css'  href='https://fonts.googleapis.com/css?family=Roboto%3A100%2C100italic%2C200%2C200italic%2C300%2C300italic%2C400%2C400italic%2C500%2C500italic%2C600%2C600italic%2C700%2C700italic%2C800%2C800italic%2C900%2C900italic%7CRoboto+Slab%3A100%2C100italic%2C200%2C200italic%2C300%2C300italic%2C400%2C400italic%2C500%2C500italic%2C600%2C600italic%2C700%2C700italic%2C800%2C800italic%2C900%2C900italic&#038;subset=vietnamese&#038;ver=5.6.2' media='all' />\r\n"
			+ "<link rel='stylesheet' id='elementor-icons-shared-0-css'  href='http://major.edu.vn/wp-content/plugins/elementor/assets/lib/font-awesome/css/fontawesome.min.css?ver=5.15.1' media='all' />\r\n"
			+ "<link rel='stylesheet' id='elementor-icons-fa-solid-css'  href='http://major.edu.vn/wp-content/plugins/elementor/assets/lib/font-awesome/css/solid.min.css?ver=5.15.1' media='all' />\r\n"
			+ "<script src='http://major.edu.vn/wp-includes/js/jquery/jquery.min.js?ver=3.5.1' id='jquery-core-js'></script>\r\n"
			+ "<script src='http://major.edu.vn/wp-includes/js/jquery/jquery-migrate.min.js?ver=3.3.2' id='jquery-migrate-js'></script>\r\n"
			+ "<link rel=\"https://api.w.org/\" href=\"http://major.edu.vn/wp-json/\" /><link rel=\"alternate\" type=\"application/json\" href=\"http://major.edu.vn/wp-json/wp/v2/pages/215\" /><link rel=\"EditURI\" type=\"application/rsd+xml\" title=\"RSD\" href=\"http://major.edu.vn/xmlrpc.php?rsd\" />\r\n"
			+ "<link rel=\"wlwmanifest\" type=\"application/wlwmanifest+xml\" href=\"http://major.edu.vn/wp-includes/wlwmanifest.xml\" /> \r\n"
			+ "<meta name=\"generator\" content=\"WordPress 5.6.2\" />\r\n"
			+ "<link rel='shortlink' href='http://major.edu.vn/' />\r\n"
			+ "<link rel=\"alternate\" type=\"application/json+oembed\" href=\"http://major.edu.vn/wp-json/oembed/1.0/embed?url=http%3A%2F%2Fmajor.edu.vn%2F\" />\r\n"
			+ "<link rel=\"alternate\" type=\"text/xml+oembed\" href=\"http://major.edu.vn/wp-json/oembed/1.0/embed?url=http%3A%2F%2Fmajor.edu.vn%2F&#038;format=xml\" />\r\n"
			+ "<!-- Google Tag Manager -->\r\n"
			+ "<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':\r\n"
			+ "new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],\r\n"
			+ "j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=\r\n"
			+ "'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);\r\n"
			+ "})(window,document,'script','dataLayer','GTM-PK3DQLJ');</script>\r\n"
			+ "<!-- End Google Tag Manager --><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><meta name=\"generator\" content=\"Powered by WPBakery Page Builder - drag and drop page builder for WordPress.\"/>\r\n"
			+ "<link rel=\"icon\" href=\"http://major.edu.vn/wp-content/uploads/2020/01/cropped-Logo-Major-Education-M-Letter-32x32.png\" sizes=\"32x32\" />\r\n"
			+ "<link rel=\"icon\" href=\"http://major.edu.vn/wp-content/uploads/2020/01/cropped-Logo-Major-Education-M-Letter-192x192.png\" sizes=\"192x192\" />\r\n"
			+ "<link rel=\"apple-touch-icon\" href=\"http://major.edu.vn/wp-content/uploads/2020/01/cropped-Logo-Major-Education-M-Letter-180x180.png\" />\r\n"
			+ "<meta name=\"msapplication-TileImage\" content=\"http://major.edu.vn/wp-content/uploads/2020/01/cropped-Logo-Major-Education-M-Letter-270x270.png\" />\r\n"
			+ "<noscript><style type=\"text/css\"> .wpb_animate_when_almost_visible { opacity: 1; }</style></noscript></head>\r\n"
			+ "\r\n"
			+ "<body class=\"home page-template page-template-elementor_header_footer page page-id-215 wp-custom-logo wp-embed-responsive post-image-aligned-center sticky-menu-fade no-sidebar nav-below-header separate-containers fluid-header active-footer-widgets-3 nav-aligned-right header-aligned-center dropdown-hover full-width-content featured-image-active wpb-js-composer js-comp-ver-6.0.1 vc_responsive elementor-default elementor-template-full-width elementor-kit-13630 elementor-page elementor-page-215\" itemtype=\"https://schema.org/WebPage\" itemscope>\r\n"
			+ "	<!-- Google Tag Manager (noscript) -->\r\n"
			+ "<noscript><iframe src=\"https://www.googletagmanager.com/ns.html?id=GTM-PK3DQLJ\"\r\n"
			+ "height=\"0\" width=\"0\" style=\"display:none;visibility:hidden\"></iframe></noscript>\r\n"
			+ "<!-- End Google Tag Manager (noscript) --><a class=\"screen-reader-text skip-link\" href=\"#content\" title=\"Chuyển đến nội dung\">Chuyển đến nội dung</a>		<nav id=\"site-navigation\" class=\"has-branding main-navigation sub-menu-right\" itemtype=\"https://schema.org/SiteNavigationElement\" itemscope>\r\n"
			+ "			<div class=\"inside-navigation grid-container grid-parent\">\r\n"
			+ "				<div class=\"navigation-branding\"><div class=\"site-logo\">\r\n"
			+ "						<a href=\"http://major.edu.vn/\" title=\"Major Education\" rel=\"home\">\r\n"
			+ "							<img  class=\"header-image is-logo-image\" alt=\"Major Education\" src=\"http://major.edu.vn/wp-content/uploads/2021/01/cropped-cropped-Major-Education-Logo1-1.png\" title=\"Major Education\" srcset=\"http://major.edu.vn/wp-content/uploads/2021/01/cropped-cropped-Major-Education-Logo1-1.png 1x, http://major.edu.vn/wp-content/uploads/2021/01/cropped-Major-Education-Logo1-1.png 2x\" width=\"2266\" height=\"2266\" />\r\n"
			+ "						</a>\r\n"
			+ "					</div></div>				\r\n"
			+ "						</div>\r\n"
			+ "		</nav>\r\n"
			+ "		<div class=\"featured-image page-header-image  grid-container grid-parent\">\r\n"
			+ "				<img width=\"950\" height=\"900\" src=\"http://major.edu.vn/wp-content/uploads/2020/10/giao-vien-major-education-2020.png\" class=\"attachment-full size-full\" alt=\"\" loading=\"lazy\" itemprop=\"image\" srcset=\"http://major.edu.vn/wp-content/uploads/2020/10/giao-vien-major-education-2020.png 950w, http://major.edu.vn/wp-content/uploads/2020/10/giao-vien-major-education-2020-300x284.png 300w, http://major.edu.vn/wp-content/uploads/2020/10/giao-vien-major-education-2020-768x728.png 768w, http://major.edu.vn/wp-content/uploads/2020/10/giao-vien-major-education-2020-255x242.png 255w\" sizes=\"(max-width: 950px) 100vw, 950px\" />\r\n"
			+ "			</div>\r\n"
			+ "	<div id=\"page\" class=\"site grid-container container hfeed grid-parent\">\r\n"
			+ "				<div id=\"content\" class=\"site-content\">\r\n"
			+ "					<div data-elementor-type=\"wp-page\" data-elementor-id=\"215\" class=\"elementor elementor-215\" data-elementor-settings=\"[]\">\r\n"
			+ "						<div class=\"elementor-inner\">\r\n"
			+ "							<div class=\"elementor-section-wrap\">\r\n"
			+ "							<section class=\"elementor-section elementor-top-section elementor-element elementor-element-6817b9d2 elementor-section-full_width elementor-section-stretched elementor-section-height-default elementor-section-height-default\" data-id=\"6817b9d2\" data-element_type=\"section\" data-settings=\"{&quot;background_background&quot;:&quot;classic&quot;,&quot;shape_divider_top&quot;:&quot;mountains&quot;,&quot;shape_divider_bottom&quot;:&quot;mountains&quot;,&quot;animation&quot;:&quot;none&quot;,&quot;stretch_section&quot;:&quot;section-stretched&quot;}\">\r\n"
			+ "							<div class=\"elementor-background-overlay\"></div>\r\n"
			+ "						<div class=\"elementor-shape elementor-shape-top\" data-negative=\"false\">\r\n"
			+ "			<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 1000 100\" preserveAspectRatio=\"none\">\r\n"
			+ "	<path class=\"elementor-shape-fill\" opacity=\"0.33\" d=\"M473,67.3c-203.9,88.3-263.1-34-320.3,0C66,119.1,0,59.7,0,59.7V0h1000v59.7 c0,0-62.1,26.1-94.9,29.3c-32.8,3.3-62.8-12.3-75.8-22.1C806,49.6,745.3,8.7,694.9,4.7S492.4,59,473,67.3z\"/>\r\n"
			+ "	<path class=\"elementor-shape-fill\" opacity=\"0.66\" d=\"M734,67.3c-45.5,0-77.2-23.2-129.1-39.1c-28.6-8.7-150.3-10.1-254,39.1 s-91.7-34.4-149.2,0C115.7,118.3,0,39.8,0,39.8V0h1000v36.5c0,0-28.2-18.5-92.1-18.5C810.2,18.1,775.7,67.3,734,67.3z\"/>\r\n"
			+ "	<path class=\"elementor-shape-fill\" d=\"M766.1,28.9c-200-57.5-266,65.5-395.1,19.5C242,1.8,242,5.4,184.8,20.6C128,35.8,132.3,44.9,89.9,52.5C28.6,63.7,0,0,0,0 h1000c0,0-9.9,40.9-83.6,48.1S829.6,47,766.1,28.9z\"/>\r\n"
			+ "</svg>		</div>\r\n"
			+ "				<div class=\"elementor-shape elementor-shape-bottom\" data-negative=\"false\">\r\n"
			+ "			<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 1000 100\" preserveAspectRatio=\"none\">\r\n"
			+ "	<path class=\"elementor-shape-fill\" opacity=\"0.33\" d=\"M473,67.3c-203.9,88.3-263.1-34-320.3,0C66,119.1,0,59.7,0,59.7V0h1000v59.7 c0,0-62.1,26.1-94.9,29.3c-32.8,3.3-62.8-12.3-75.8-22.1C806,49.6,745.3,8.7,694.9,4.7S492.4,59,473,67.3z\"/>\r\n"
			+ "	<path class=\"elementor-shape-fill\" opacity=\"0.66\" d=\"M734,67.3c-45.5,0-77.2-23.2-129.1-39.1c-28.6-8.7-150.3-10.1-254,39.1 s-91.7-34.4-149.2,0C115.7,118.3,0,39.8,0,39.8V0h1000v36.5c0,0-28.2-18.5-92.1-18.5C810.2,18.1,775.7,67.3,734,67.3z\"/>\r\n"
			+ "	<path class=\"elementor-shape-fill\" d=\"M766.1,28.9c-200-57.5-266,65.5-395.1,19.5C242,1.8,242,5.4,184.8,20.6C128,35.8,132.3,44.9,89.9,52.5C28.6,63.7,0,0,0,0 h1000c0,0-9.9,40.9-83.6,48.1S829.6,47,766.1,28.9z\"/>\r\n"
			+ "</svg>		</div>\r\n"
			+ "					<div class=\"elementor-container elementor-column-gap-default\">\r\n"
			+ "							<div class=\"elementor-row\">\r\n"
			+ "					<div class=\"elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-48883bf7\" data-id=\"48883bf7\" data-element_type=\"column\">\r\n"
			+ "			<div class=\"elementor-column-wrap elementor-element-populated\">\r\n"
			+ "							<div class=\"elementor-widget-wrap\">\r\n"
			+ "						<div class=\"elementor-element elementor-element-7b70b00d elementor-widget elementor-widget-heading\" data-id=\"7b70b00d\" data-element_type=\"widget\" data-widget_type=\"heading.default\">\r\n"
			+ "				<div class=\"elementor-widget-container\">\r\n"
			+ "			<h1 class=\"elementor-heading-title elementor-size-xxl\"><b>Major Education</b></h1>		</div>\r\n"
			+ "				</div>\r\n"
			+ "				<section class=\"elementor-section elementor-inner-section elementor-element elementor-element-73e8a56 elementor-section-boxed elementor-section-height-default elementor-section-height-default\" data-id=\"73e8a56\" data-element_type=\"section\">\r\n"
			+ "						<div class=\"elementor-container elementor-column-gap-default\">\r\n"
			+ "							<div class=\"elementor-row\">\r\n"
			+ "					<div class=\"elementor-column elementor-col-100 elementor-inner-column elementor-element elementor-element-1a30f5ea\" data-id=\"1a30f5ea\" data-element_type=\"column\">\r\n"
			+ "			<div class=\"elementor-column-wrap elementor-element-populated\">\r\n"
			+ "							<div class=\"elementor-widget-wrap\">\r\n"
			+ "						<div class=\"elementor-element elementor-element-435c54cb elementor-widget__width-initial elementor-widget elementor-widget-text-editor\" data-id=\"435c54cb\" data-element_type=\"widget\" data-widget_type=\"text-editor.default\">\r\n"
			+ "				<div class=\"elementor-widget-container\">\r\n"
			+ "					<div class=\"elementor-text-editor elementor-clearfix\"><p>Giỏi tiếng Anh, Nhanh thành tài</p></div>\r\n"
			+ "				</div>\r\n"
			+ "				</div>\r\n"
			+ "				<div class=\"elementor-element elementor-element-15c2e88d elementor-align-center elementor-widget elementor-widget-button\" data-id=\"15c2e88d\" data-element_type=\"widget\" data-widget_type=\"button.default\">\r\n"
			+ "				<div class=\"elementor-widget-container\">\r\n"
			+ "					<div class=\"elementor-button-wrapper\">\r\n"
			+ "			<a  class=\"elementor-button-link elementor-button elementor-size-lg elementor-animation-grow\" role=\"button\">\r\n"
			+ "						<span class=\"elementor-button-content-wrapper\">\r\n"
			+ "						<span class=\"elementor-button-text\">Your Password here</span>\r\n"
			+ "		</span>\r\n"
			+ "					</a>\r\n"
			+ "		</div>\r\n"
			+ "				</div>\r\n"
			+ "				</div>\r\n"
			+ "						</div>\r\n"
			+ "					</div>\r\n"
			+ "		</div>\r\n"
			+ "								</div>\r\n"
			+ "					</div>\r\n"
			+ "		</section>\r\n"
			+ "						</div>\r\n"
			+ "					</div>\r\n"
			+ "		</div>\r\n"
			+ "								</div>\r\n"
			+ "					</div>\r\n"
			+ "		</section>\r\n"
			+ "				<section class=\"elementor-section elementor-top-section elementor-element elementor-element-1fa8f343 elementor-section-stretched elementor-section-height-min-height elementor-section-items-stretch elementor-section-boxed elementor-section-height-default elementor-invisible\" data-id=\"1fa8f343\" data-element_type=\"section\" data-settings=\"{&quot;background_background&quot;:&quot;classic&quot;,&quot;stretch_section&quot;:&quot;section-stretched&quot;,&quot;shape_divider_bottom&quot;:&quot;waves&quot;,&quot;animation&quot;:&quot;fadeIn&quot;}\">\r\n"
			+ "					<div class=\"elementor-shape elementor-shape-bottom\" data-negative=\"false\">\r\n"
			+ "			<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 1000 100\" preserveAspectRatio=\"none\">\r\n"
			+ "	<path class=\"elementor-shape-fill\" d=\"M421.9,6.5c22.6-2.5,51.5,0.4,75.5,5.3c23.6,4.9,70.9,23.5,100.5,35.7c75.8,32.2,133.7,44.5,192.6,49.7\r\n"
			+ "	c23.6,2.1,48.7,3.5,103.4-2.5c54.7-6,106.2-25.6,106.2-25.6V0H0v30.3c0,0,72,32.6,158.4,30.5c39.2-0.7,92.8-6.7,134-22.4\r\n"
			+ "	c21.2-8.1,52.2-18.2,79.7-24.2C399.3,7.9,411.6,7.5,421.9,6.5z\"/>\r\n"
			+ "</svg>		</div>\r\n"
			+ "					<div class=\"elementor-container elementor-column-gap-default\">\r\n"
			+ "							<div class=\"elementor-row\">\r\n"
			+ "					<div class=\"elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-25d42ae6\" data-id=\"25d42ae6\" data-element_type=\"column\">\r\n"
			+ "			<div class=\"elementor-column-wrap elementor-element-populated\">\r\n"
			+ "							<div class=\"elementor-widget-wrap\">\r\n"
			+ "						<div class=\"elementor-element elementor-element-631abe2a elementor-widget elementor-widget-heading\" data-id=\"631abe2a\" data-element_type=\"widget\" data-widget_type=\"heading.default\">\r\n"
			+ "				<div class=\"elementor-widget-container\">\r\n"
			+ "			<h2 class=\"elementor-heading-title elementor-size-default\"><b>Liên Hệ Tư Vấn &amp; </b><br><b>Hợp Tác</b></h2>		</div>\r\n"
			+ "				</div>\r\n"
			+ "				<div class=\"elementor-element elementor-element-66feb966 elementor-widget elementor-widget-text-editor\" data-id=\"66feb966\" data-element_type=\"widget\" data-widget_type=\"text-editor.default\">\r\n"
			+ "				<div class=\"elementor-widget-container\">\r\n"
			+ "					<div class=\"elementor-text-editor elementor-clearfix\"><p>Đội ngũ chuyên viên giáo dục tại  Major Education luôn sẵn sàng hỗ trợ!</p></div>\r\n"
			+ "				</div>\r\n"
			+ "				</div>\r\n"
			+ "				<div class=\"elementor-element elementor-element-1a277c0a elementor-align-left elementor-list-item-link-full_width elementor-widget elementor-widget-icon-list\" data-id=\"1a277c0a\" data-element_type=\"widget\" data-widget_type=\"icon-list.default\">\r\n"
			+ "				<div class=\"elementor-widget-container\">\r\n"
			+ "					<ul class=\"elementor-icon-list-items\">\r\n"
			+ "							<li class=\"elementor-icon-list-item\">\r\n"
			+ "											<span class=\"elementor-icon-list-icon\">\r\n"
			+ "							<i aria-hidden=\"true\" class=\"fas fa-map-marker-alt\"></i>						</span>\r\n"
			+ "										<span class=\"elementor-icon-list-text\">269A Nguyễn Trọng Tuyển, P.10, Quận Phú Nhuận, TP.HCM</span>\r\n"
			+ "									</li>\r\n"
			+ "								<li class=\"elementor-icon-list-item\">\r\n"
			+ "					<a href=\"mailto:huyen@truongvietanh.com\">						<span class=\"elementor-icon-list-icon\">\r\n"
			+ "							<i aria-hidden=\"true\" class=\"fas fa-envelope\"></i>						</span>\r\n"
			+ "										<span class=\"elementor-icon-list-text\">huyen@truongvietanh.com</span>\r\n"
			+ "											</a>\r\n"
			+ "									</li>\r\n"
			+ "								<li class=\"elementor-icon-list-item\">\r\n"
			+ "					<a href=\"tel:098%20438%2089%2088\">						<span class=\"elementor-icon-list-icon\">\r\n"
			+ "							<i aria-hidden=\"true\" class=\"fas fa-phone-alt\"></i>						</span>\r\n"
			+ "										<span class=\"elementor-icon-list-text\">098 438 89 88 - Cô Mai Huyên</span>\r\n"
			+ "											</a>\r\n"
			+ "									</li>\r\n"
			+ "								<li class=\"elementor-icon-list-item\">\r\n"
			+ "											<span class=\"elementor-icon-list-icon\">\r\n"
			+ "							<i aria-hidden=\"true\" class=\"fas fa-check\"></i>						</span>\r\n"
			+ "										<span class=\"elementor-icon-list-text\">GPHĐKD Số: 746/QĐ-GDĐT-TC</span>\r\n"
			+ "									</li>\r\n"
			+ "								<li class=\"elementor-icon-list-item\">\r\n"
			+ "											<span class=\"elementor-icon-list-icon\">\r\n"
			+ "							<i aria-hidden=\"true\" class=\"fas fa-check\"></i>						</span>\r\n"
			+ "										<span class=\"elementor-icon-list-text\">Giấy phép thành lập số: 349/QĐ-GDĐT-TC</span>\r\n"
			+ "									</li>\r\n"
			+ "						</ul>\r\n"
			+ "				</div>\r\n"
			+ "				</div>\r\n"
			+ "						</div>\r\n"
			+ "					</div>\r\n"
			+ "		</div>\r\n"
			+ "				<div class=\"elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-18faf111\" data-id=\"18faf111\" data-element_type=\"column\">\r\n"
			+ "			<div class=\"elementor-column-wrap elementor-element-populated\">\r\n"
			+ "							<div class=\"elementor-widget-wrap\">\r\n"
			+ "						<div class=\"elementor-element elementor-element-5a3316c4 elementor-widget elementor-widget-google_maps\" data-id=\"5a3316c4\" data-element_type=\"widget\" data-widget_type=\"google_maps.default\">\r\n"
			+ "				<div class=\"elementor-widget-container\">\r\n"
			+ "			<div class=\"elementor-custom-embed\"><iframe frameborder=\"0\" scrolling=\"no\" marginheight=\"0\" marginwidth=\"0\" src=\"https://maps.google.com/maps?q=269a%20nguy%E1%BB%85n%20tr%E1%BB%8Dng%20tuy%E1%BB%83n&amp;t=m&amp;z=12&amp;output=embed&amp;iwloc=near\" title=\"269a nguyễn trọng tuyển\" aria-label=\"269a nguyễn trọng tuyển\"></iframe></div>		</div>\r\n"
			+ "				</div>\r\n"
			+ "						</div>\r\n"
			+ "					</div>\r\n"
			+ "		</div>\r\n"
			+ "								</div>\r\n"
			+ "					</div>\r\n"
			+ "		</section>\r\n"
			+ "						</div>\r\n"
			+ "						</div>\r\n"
			+ "					</div>\r\n"
			+ "		\r\n"
			+ "	</div>\r\n"
			+ "</div>\r\n"
			+ "\r\n"
			+ "\r\n"
			+ "<div class=\"site-footer\">\r\n"
			+ "			<footer class=\"site-info\" itemtype=\"https://schema.org/WPFooter\" itemscope>\r\n"
			+ "			<div class=\"inside-site-info grid-container grid-parent\">\r\n"
			+ "								<div class=\"copyright-bar\">\r\n"
			+ "					Major Education - Giỏi Tiếng Anh, Nhanh Thành Tài				</div>\r\n"
			+ "			</div>\r\n"
			+ "		</footer>\r\n"
			+ "		</div>\r\n"
			+ "\r\n"
			+ "<link rel='stylesheet' id='font-awesome-5-all-css'  href='http://major.edu.vn/wp-content/plugins/elementor/assets/lib/font-awesome/css/all.min.css?ver=4.5.0' media='all' />\r\n"
			+ "<link rel='stylesheet' id='font-awesome-4-shim-css'  href='http://major.edu.vn/wp-content/plugins/elementor/assets/lib/font-awesome/css/v4-shims.min.css?ver=4.5.0' media='all' />\r\n"
			+ "<script id='cb70d11b8-js-extra'>\r\n"
			+ "var localize = {\"ajaxurl\":\"http:\\/\\/major.edu.vn\\/wp-admin\\/admin-ajax.php\",\"nonce\":\"16afdcd49a\",\"i18n\":{\"added\":\"Added \",\"compare\":\"Compare\",\"loading\":\"Loading...\"}};\r\n"
			+ "</script>\r\n"
			+ "<script src='http://major.edu.vn/wp-content/uploads/essential-addons-elementor/cb70d11b8.min.js?ver=1616279248' id='cb70d11b8-js'></script>\r\n"
			+ "<!--[if lte IE 11]>\r\n"
			+ "<script src='http://major.edu.vn/wp-content/themes/generatepress/assets/js/classList.min.js?ver=3.0.2' id='generate-classlist-js'></script>\r\n"
			+ "<![endif]-->\r\n"
			+ "<script id='generate-main-js-extra'>\r\n"
			+ "var generatepressMenu = {\"toggleOpenedSubMenus\":\"1\",\"openSubMenuLabel\":\"Open Sub-Menu\",\"closeSubMenuLabel\":\"Close Sub-Menu\"};\r\n"
			+ "</script>\r\n"
			+ "<script src='http://major.edu.vn/wp-content/themes/generatepress/assets/js/main.min.js?ver=3.0.2' id='generate-main-js'></script>\r\n"
			+ "<script src='http://major.edu.vn/wp-includes/js/wp-embed.min.js?ver=5.6.2' id='wp-embed-js'></script>\r\n"
			+ "<script src='http://major.edu.vn/wp-content/plugins/elementor/assets/lib/jquery-numerator/jquery-numerator.min.js?ver=0.2.1' id='jquery-numerator-js'></script>\r\n"
			+ "<script src='http://major.edu.vn/wp-content/plugins/elementor/assets/js/webpack.runtime.min.js?ver=3.1.1' id='elementor-webpack-runtime-js'></script>\r\n"
			+ "<script src='http://major.edu.vn/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.1.1' id='elementor-frontend-modules-js'></script>\r\n"
			+ "<script src='http://major.edu.vn/wp-includes/js/jquery/ui/core.min.js?ver=1.12.1' id='jquery-ui-core-js'></script>\r\n"
			+ "<script src='http://major.edu.vn/wp-content/plugins/elementor/assets/lib/dialog/dialog.min.js?ver=4.8.1' id='elementor-dialog-js'></script>\r\n"
			+ "<script src='http://major.edu.vn/wp-content/plugins/elementor/assets/lib/waypoints/waypoints.min.js?ver=4.0.2' id='elementor-waypoints-js'></script>\r\n"
			+ "<script src='http://major.edu.vn/wp-content/plugins/elementor/assets/lib/share-link/share-link.min.js?ver=3.1.1' id='share-link-js'></script>\r\n"
			+ "<script src='http://major.edu.vn/wp-content/plugins/elementor/assets/lib/swiper/swiper.min.js?ver=5.3.6' id='swiper-js'></script>\r\n"
			+ "<script id='elementor-frontend-js-before'>\r\n"
			+ "var elementorFrontendConfig = {\"environmentMode\":{\"edit\":false,\"wpPreview\":false,\"isScriptDebug\":false,\"isImprovedAssetsLoading\":false},\"i18n\":{\"shareOnFacebook\":\"Share on Facebook\",\"shareOnTwitter\":\"Share on Twitter\",\"pinIt\":\"Pin it\",\"download\":\"Download\",\"downloadImage\":\"Download image\",\"fullscreen\":\"Fullscreen\",\"zoom\":\"Thu ph\\u00f3ng\",\"share\":\"Share\",\"playVideo\":\"Ch\\u01a1i Video\",\"previous\":\"Previous\",\"next\":\"Next\",\"close\":\"\\u0110\\u00f3ng\"},\"is_rtl\":false,\"breakpoints\":{\"xs\":0,\"sm\":480,\"md\":768,\"lg\":1025,\"xl\":1440,\"xxl\":1600},\"version\":\"3.1.1\",\"is_static\":false,\"experimentalFeatures\":[],\"urls\":{\"assets\":\"http:\\/\\/major.edu.vn\\/wp-content\\/plugins\\/elementor\\/assets\\/\"},\"settings\":{\"page\":[],\"editorPreferences\":[]},\"kit\":{\"global_image_lightbox\":\"yes\",\"lightbox_enable_counter\":\"yes\",\"lightbox_enable_fullscreen\":\"yes\",\"lightbox_enable_zoom\":\"yes\",\"lightbox_enable_share\":\"yes\",\"lightbox_title_src\":\"title\",\"lightbox_description_src\":\"description\"},\"post\":{\"id\":215,\"title\":\"Major%20Education%20%E2%80%93%20Gi%E1%BB%8Fi%20Ti%E1%BA%BFng%20Anh%2C%20Nhanh%20Th%C3%A0nh%20T%C3%A0i\",\"excerpt\":\"\",\"featuredImage\":\"http:\\/\\/major.edu.vn\\/wp-content\\/uploads\\/2020\\/10\\/giao-vien-major-education-2020.png\"}};\r\n"
			+ "</script>\r\n"
			+ "<script src='http://major.edu.vn/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.1.1' id='elementor-frontend-js'></script>\r\n"
			+ "<script src='http://major.edu.vn/wp-content/plugins/elementor/assets/js/preloaded-elements-handlers.min.js?ver=3.1.1' id='preloaded-elements-handlers-js'></script>\r\n"
			+ "\r\n"
			+ "</body>\r\n"
			+ "</html>\r\n"
			+ "";
}
